//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("RightsManagementSystemModel", "SysPerSonSysPersonToPosition", "SysPerSon", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RightsManagementSystem.Entity.SysPerson), "SysPersonToPosition", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RightsManagementSystem.Entity.SysPersonToPosition), true)]
[assembly: EdmRelationshipAttribute("RightsManagementSystemModel", "SysPositionSysPersonToPosition", "SysPosition", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RightsManagementSystem.Entity.SysPosition), "SysPersonToPosition", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RightsManagementSystem.Entity.SysPersonToPosition), true)]
[assembly: EdmRelationshipAttribute("RightsManagementSystemModel", "SysPositionSysDepartment", "SysPosition", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RightsManagementSystem.Entity.SysPosition), "SysDepartment", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RightsManagementSystem.Entity.SysDepartment), true)]
[assembly: EdmRelationshipAttribute("RightsManagementSystemModel", "SysPersonOrPositionToRoleSysRole", "SysPersonOrPositionToRole", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RightsManagementSystem.Entity.SysPersonOrPositionToRole), "SysRole", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RightsManagementSystem.Entity.SysRole), true)]
[assembly: EdmRelationshipAttribute("RightsManagementSystemModel", "SysRoleToRightsSysRightsMenu", "SysRoleToRights", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RightsManagementSystem.Entity.SysRoleToRights), "SysRightsMenu", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RightsManagementSystem.Entity.SysRightsMenu), true)]
[assembly: EdmRelationshipAttribute("RightsManagementSystemModel", "SysPositionSysPosition", "SysPosition", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RightsManagementSystem.Entity.SysPosition), "SysPosition1", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RightsManagementSystem.Entity.SysPosition), true)]
[assembly: EdmRelationshipAttribute("RightsManagementSystemModel", "SysDepartmentSysDepartment", "SysDepartment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RightsManagementSystem.Entity.SysDepartment), "SysDepartment1", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RightsManagementSystem.Entity.SysDepartment), true)]

#endregion

namespace RightsManagementSystem.Entity
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class RightsManagementSystemEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“RightsManagementSystemEntities”部分中的连接字符串初始化新 RightsManagementSystemEntities 对象。
        /// </summary>
        public RightsManagementSystemEntities() : base("name=RightsManagementSystemEntities", "RightsManagementSystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 RightsManagementSystemEntities 对象。
        /// </summary>
        public RightsManagementSystemEntities(string connectionString) : base(connectionString, "RightsManagementSystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 RightsManagementSystemEntities 对象。
        /// </summary>
        public RightsManagementSystemEntities(EntityConnection connection) : base(connection, "RightsManagementSystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SysPerson> SysPerson
        {
            get
            {
                if ((_SysPerson == null))
                {
                    _SysPerson = base.CreateObjectSet<SysPerson>("SysPerson");
                }
                return _SysPerson;
            }
        }
        private ObjectSet<SysPerson> _SysPerson;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SysPosition> SysPosition
        {
            get
            {
                if ((_SysPosition == null))
                {
                    _SysPosition = base.CreateObjectSet<SysPosition>("SysPosition");
                }
                return _SysPosition;
            }
        }
        private ObjectSet<SysPosition> _SysPosition;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SysPersonToPosition> SysPersonToPosition
        {
            get
            {
                if ((_SysPersonToPosition == null))
                {
                    _SysPersonToPosition = base.CreateObjectSet<SysPersonToPosition>("SysPersonToPosition");
                }
                return _SysPersonToPosition;
            }
        }
        private ObjectSet<SysPersonToPosition> _SysPersonToPosition;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SysRole> SysRole
        {
            get
            {
                if ((_SysRole == null))
                {
                    _SysRole = base.CreateObjectSet<SysRole>("SysRole");
                }
                return _SysRole;
            }
        }
        private ObjectSet<SysRole> _SysRole;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SysPersonOrPositionToRole> SysPersonOrPositionToRole
        {
            get
            {
                if ((_SysPersonOrPositionToRole == null))
                {
                    _SysPersonOrPositionToRole = base.CreateObjectSet<SysPersonOrPositionToRole>("SysPersonOrPositionToRole");
                }
                return _SysPersonOrPositionToRole;
            }
        }
        private ObjectSet<SysPersonOrPositionToRole> _SysPersonOrPositionToRole;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SysDepartment> SysDepartment
        {
            get
            {
                if ((_SysDepartment == null))
                {
                    _SysDepartment = base.CreateObjectSet<SysDepartment>("SysDepartment");
                }
                return _SysDepartment;
            }
        }
        private ObjectSet<SysDepartment> _SysDepartment;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SysRoleToRights> SysRoleToRights
        {
            get
            {
                if ((_SysRoleToRights == null))
                {
                    _SysRoleToRights = base.CreateObjectSet<SysRoleToRights>("SysRoleToRights");
                }
                return _SysRoleToRights;
            }
        }
        private ObjectSet<SysRoleToRights> _SysRoleToRights;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SysRightsMenu> SysRightsMenu
        {
            get
            {
                if ((_SysRightsMenu == null))
                {
                    _SysRightsMenu = base.CreateObjectSet<SysRightsMenu>("SysRightsMenu");
                }
                return _SysRightsMenu;
            }
        }
        private ObjectSet<SysRightsMenu> _SysRightsMenu;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Menu> Menu
        {
            get
            {
                if ((_Menu == null))
                {
                    _Menu = base.CreateObjectSet<Menu>("Menu");
                }
                return _Menu;
            }
        }
        private ObjectSet<Menu> _Menu;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SystemSetting> SystemSetting
        {
            get
            {
                if ((_SystemSetting == null))
                {
                    _SystemSetting = base.CreateObjectSet<SystemSetting>("SystemSetting");
                }
                return _SystemSetting;
            }
        }
        private ObjectSet<SystemSetting> _SystemSetting;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 SysPerson EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSysPerson(SysPerson sysPerson)
        {
            base.AddObject("SysPerson", sysPerson);
        }
    
        /// <summary>
        /// 用于向 SysPosition EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSysPosition(SysPosition sysPosition)
        {
            base.AddObject("SysPosition", sysPosition);
        }
    
        /// <summary>
        /// 用于向 SysPersonToPosition EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSysPersonToPosition(SysPersonToPosition sysPersonToPosition)
        {
            base.AddObject("SysPersonToPosition", sysPersonToPosition);
        }
    
        /// <summary>
        /// 用于向 SysRole EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSysRole(SysRole sysRole)
        {
            base.AddObject("SysRole", sysRole);
        }
    
        /// <summary>
        /// 用于向 SysPersonOrPositionToRole EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSysPersonOrPositionToRole(SysPersonOrPositionToRole sysPersonOrPositionToRole)
        {
            base.AddObject("SysPersonOrPositionToRole", sysPersonOrPositionToRole);
        }
    
        /// <summary>
        /// 用于向 SysDepartment EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSysDepartment(SysDepartment sysDepartment)
        {
            base.AddObject("SysDepartment", sysDepartment);
        }
    
        /// <summary>
        /// 用于向 SysRoleToRights EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSysRoleToRights(SysRoleToRights sysRoleToRights)
        {
            base.AddObject("SysRoleToRights", sysRoleToRights);
        }
    
        /// <summary>
        /// 用于向 SysRightsMenu EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSysRightsMenu(SysRightsMenu sysRightsMenu)
        {
            base.AddObject("SysRightsMenu", sysRightsMenu);
        }
    
        /// <summary>
        /// 用于向 Menu EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMenu(Menu menu)
        {
            base.AddObject("Menu", menu);
        }
    
        /// <summary>
        /// 用于向 SystemSetting EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSystemSetting(SystemSetting systemSetting)
        {
            base.AddObject("SystemSetting", systemSetting);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RightsManagementSystemModel", Name="Menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Menu : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Menu 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="url">Url 属性的初始值。</param>
        /// <param name="iconic">Iconic 属性的初始值。</param>
        /// <param name="sort">Sort 属性的初始值。</param>
        /// <param name="remark">Remark 属性的初始值。</param>
        /// <param name="status">Status 属性的初始值。</param>
        public static Menu CreateMenu(global::System.String id, global::System.String name, global::System.String url, global::System.String iconic, global::System.String sort, global::System.String remark, global::System.String status)
        {
            Menu menu = new Menu();
            menu.ID = id;
            menu.Name = name;
            menu.Url = url;
            menu.Iconic = iconic;
            menu.Sort = sort;
            menu.Remark = remark;
            menu.Status = status;
            return menu;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private global::System.String _ParentId;
        partial void OnParentIdChanging(global::System.String value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Iconic
        {
            get
            {
                return _Iconic;
            }
            set
            {
                OnIconicChanging(value);
                ReportPropertyChanging("Iconic");
                _Iconic = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Iconic");
                OnIconicChanged();
            }
        }
        private global::System.String _Iconic;
        partial void OnIconicChanging(global::System.String value);
        partial void OnIconicChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sort
        {
            get
            {
                return _Sort;
            }
            set
            {
                OnSortChanging(value);
                ReportPropertyChanging("Sort");
                _Sort = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sort");
                OnSortChanged();
            }
        }
        private global::System.String _Sort;
        partial void OnSortChanging(global::System.String value);
        partial void OnSortChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RightsManagementSystemModel", Name="SysDepartment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysDepartment : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SysDepartment 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="departmentName">DepartmentName 属性的初始值。</param>
        /// <param name="parentId">ParentId 属性的初始值。</param>
        /// <param name="sort">Sort 属性的初始值。</param>
        /// <param name="remark">Remark 属性的初始值。</param>
        /// <param name="status">Status 属性的初始值。</param>
        public static SysDepartment CreateSysDepartment(global::System.String id, global::System.String departmentName, global::System.String parentId, global::System.String sort, global::System.String remark, global::System.String status)
        {
            SysDepartment sysDepartment = new SysDepartment();
            sysDepartment.ID = id;
            sysDepartment.DepartmentName = departmentName;
            sysDepartment.ParentId = parentId;
            sysDepartment.Sort = sort;
            sysDepartment.Remark = remark;
            sysDepartment.Status = status;
            return sysDepartment;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private global::System.String _ParentId;
        partial void OnParentIdChanging(global::System.String value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sort
        {
            get
            {
                return _Sort;
            }
            set
            {
                OnSortChanging(value);
                ReportPropertyChanging("Sort");
                _Sort = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sort");
                OnSortChanged();
            }
        }
        private global::System.String _Sort;
        partial void OnSortChanging(global::System.String value);
        partial void OnSortChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RightsManagementSystemModel", "SysPositionSysDepartment", "SysPosition")]
        public EntityCollection<SysPosition> SysPosition
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SysPosition>("RightsManagementSystemModel.SysPositionSysDepartment", "SysPosition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SysPosition>("RightsManagementSystemModel.SysPositionSysDepartment", "SysPosition", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RightsManagementSystemModel", "SysDepartmentSysDepartment", "SysDepartment1")]
        public SysDepartment SysDepartmentParent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysDepartment>("RightsManagementSystemModel.SysDepartmentSysDepartment", "SysDepartment1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysDepartment>("RightsManagementSystemModel.SysDepartmentSysDepartment", "SysDepartment1").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SysDepartment> SysDepartmentParentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysDepartment>("RightsManagementSystemModel.SysDepartmentSysDepartment", "SysDepartment1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SysDepartment>("RightsManagementSystemModel.SysDepartmentSysDepartment", "SysDepartment1", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RightsManagementSystemModel", Name="SysPerson")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysPerson : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SysPerson 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="account">Account 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="passWord">PassWord 属性的初始值。</param>
        public static SysPerson CreateSysPerson(global::System.String id, global::System.String account, global::System.String name, global::System.String passWord)
        {
            SysPerson sysPerson = new SysPerson();
            sysPerson.ID = id;
            sysPerson.Account = account;
            sysPerson.Name = name;
            sysPerson.PassWord = passWord;
            return sysPerson;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Account
        {
            get
            {
                return _Account;
            }
            set
            {
                OnAccountChanging(value);
                ReportPropertyChanging("Account");
                _Account = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Account");
                OnAccountChanged();
            }
        }
        private global::System.String _Account;
        partial void OnAccountChanging(global::System.String value);
        partial void OnAccountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PassWord
        {
            get
            {
                return _PassWord;
            }
            set
            {
                OnPassWordChanging(value);
                ReportPropertyChanging("PassWord");
                _PassWord = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PassWord");
                OnPassWordChanged();
            }
        }
        private global::System.String _PassWord;
        partial void OnPassWordChanging(global::System.String value);
        partial void OnPassWordChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RightsManagementSystemModel", "SysPerSonSysPersonToPosition", "SysPersonToPosition")]
        public EntityCollection<SysPersonToPosition> SysPersonToPosition
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SysPersonToPosition>("RightsManagementSystemModel.SysPerSonSysPersonToPosition", "SysPersonToPosition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SysPersonToPosition>("RightsManagementSystemModel.SysPerSonSysPersonToPosition", "SysPersonToPosition", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RightsManagementSystemModel", Name="SysPersonOrPositionToRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysPersonOrPositionToRole : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SysPersonOrPositionToRole 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="roleId">RoleId 属性的初始值。</param>
        /// <param name="perSonOrPositionId">PerSonOrPositionId 属性的初始值。</param>
        public static SysPersonOrPositionToRole CreateSysPersonOrPositionToRole(global::System.String id, global::System.String roleId, global::System.String perSonOrPositionId)
        {
            SysPersonOrPositionToRole sysPersonOrPositionToRole = new SysPersonOrPositionToRole();
            sysPersonOrPositionToRole.ID = id;
            sysPersonOrPositionToRole.RoleId = roleId;
            sysPersonOrPositionToRole.PerSonOrPositionId = perSonOrPositionId;
            return sysPersonOrPositionToRole;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private global::System.String _RoleId;
        partial void OnRoleIdChanging(global::System.String value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PerSonOrPositionId
        {
            get
            {
                return _PerSonOrPositionId;
            }
            set
            {
                OnPerSonOrPositionIdChanging(value);
                ReportPropertyChanging("PerSonOrPositionId");
                _PerSonOrPositionId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PerSonOrPositionId");
                OnPerSonOrPositionIdChanged();
            }
        }
        private global::System.String _PerSonOrPositionId;
        partial void OnPerSonOrPositionIdChanging(global::System.String value);
        partial void OnPerSonOrPositionIdChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RightsManagementSystemModel", "SysPersonOrPositionToRoleSysRole", "SysRole")]
        public SysRole SysRole
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysRole>("RightsManagementSystemModel.SysPersonOrPositionToRoleSysRole", "SysRole").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysRole>("RightsManagementSystemModel.SysPersonOrPositionToRoleSysRole", "SysRole").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SysRole> SysRoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysRole>("RightsManagementSystemModel.SysPersonOrPositionToRoleSysRole", "SysRole");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SysRole>("RightsManagementSystemModel.SysPersonOrPositionToRoleSysRole", "SysRole", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RightsManagementSystemModel", Name="SysPersonToPosition")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysPersonToPosition : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SysPersonToPosition 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="personId">PersonId 属性的初始值。</param>
        /// <param name="positionId">PositionId 属性的初始值。</param>
        /// <param name="flagPrimacy">FlagPrimacy 属性的初始值。</param>
        public static SysPersonToPosition CreateSysPersonToPosition(global::System.String id, global::System.String personId, global::System.String positionId, global::System.String flagPrimacy)
        {
            SysPersonToPosition sysPersonToPosition = new SysPersonToPosition();
            sysPersonToPosition.ID = id;
            sysPersonToPosition.PersonId = personId;
            sysPersonToPosition.PositionId = positionId;
            sysPersonToPosition.FlagPrimacy = flagPrimacy;
            return sysPersonToPosition;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PersonId
        {
            get
            {
                return _PersonId;
            }
            set
            {
                OnPersonIdChanging(value);
                ReportPropertyChanging("PersonId");
                _PersonId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PersonId");
                OnPersonIdChanged();
            }
        }
        private global::System.String _PersonId;
        partial void OnPersonIdChanging(global::System.String value);
        partial void OnPersonIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PositionId
        {
            get
            {
                return _PositionId;
            }
            set
            {
                OnPositionIdChanging(value);
                ReportPropertyChanging("PositionId");
                _PositionId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PositionId");
                OnPositionIdChanged();
            }
        }
        private global::System.String _PositionId;
        partial void OnPositionIdChanging(global::System.String value);
        partial void OnPositionIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FlagPrimacy
        {
            get
            {
                return _FlagPrimacy;
            }
            set
            {
                OnFlagPrimacyChanging(value);
                ReportPropertyChanging("FlagPrimacy");
                _FlagPrimacy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FlagPrimacy");
                OnFlagPrimacyChanged();
            }
        }
        private global::System.String _FlagPrimacy;
        partial void OnFlagPrimacyChanging(global::System.String value);
        partial void OnFlagPrimacyChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RightsManagementSystemModel", "SysPerSonSysPersonToPosition", "SysPerSon")]
        public SysPerson SysPerSon
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysPerson>("RightsManagementSystemModel.SysPerSonSysPersonToPosition", "SysPerSon").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysPerson>("RightsManagementSystemModel.SysPerSonSysPersonToPosition", "SysPerSon").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SysPerson> SysPerSonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysPerson>("RightsManagementSystemModel.SysPerSonSysPersonToPosition", "SysPerSon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SysPerson>("RightsManagementSystemModel.SysPerSonSysPersonToPosition", "SysPerSon", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RightsManagementSystemModel", "SysPositionSysPersonToPosition", "SysPosition")]
        public SysPosition SysPosition
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysPosition>("RightsManagementSystemModel.SysPositionSysPersonToPosition", "SysPosition").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysPosition>("RightsManagementSystemModel.SysPositionSysPersonToPosition", "SysPosition").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SysPosition> SysPositionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysPosition>("RightsManagementSystemModel.SysPositionSysPersonToPosition", "SysPosition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SysPosition>("RightsManagementSystemModel.SysPositionSysPersonToPosition", "SysPosition", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RightsManagementSystemModel", Name="SysPosition")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysPosition : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SysPosition 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="positionId">PositionId 属性的初始值。</param>
        /// <param name="positionName">PositionName 属性的初始值。</param>
        /// <param name="parentId">ParentId 属性的初始值。</param>
        /// <param name="departmentId">DepartmentId 属性的初始值。</param>
        public static SysPosition CreateSysPosition(global::System.String id, global::System.String positionId, global::System.String positionName, global::System.String parentId, global::System.String departmentId)
        {
            SysPosition sysPosition = new SysPosition();
            sysPosition.ID = id;
            sysPosition.PositionId = positionId;
            sysPosition.PositionName = positionName;
            sysPosition.ParentId = parentId;
            sysPosition.DepartmentId = departmentId;
            return sysPosition;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PositionId
        {
            get
            {
                return _PositionId;
            }
            set
            {
                OnPositionIdChanging(value);
                ReportPropertyChanging("PositionId");
                _PositionId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PositionId");
                OnPositionIdChanged();
            }
        }
        private global::System.String _PositionId;
        partial void OnPositionIdChanging(global::System.String value);
        partial void OnPositionIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PositionName
        {
            get
            {
                return _PositionName;
            }
            set
            {
                OnPositionNameChanging(value);
                ReportPropertyChanging("PositionName");
                _PositionName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PositionName");
                OnPositionNameChanged();
            }
        }
        private global::System.String _PositionName;
        partial void OnPositionNameChanging(global::System.String value);
        partial void OnPositionNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private global::System.String _ParentId;
        partial void OnParentIdChanging(global::System.String value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DepartmentId
        {
            get
            {
                return _DepartmentId;
            }
            set
            {
                OnDepartmentIdChanging(value);
                ReportPropertyChanging("DepartmentId");
                _DepartmentId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DepartmentId");
                OnDepartmentIdChanged();
            }
        }
        private global::System.String _DepartmentId;
        partial void OnDepartmentIdChanging(global::System.String value);
        partial void OnDepartmentIdChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RightsManagementSystemModel", "SysPositionSysPersonToPosition", "SysPersonToPosition")]
        public EntityCollection<SysPersonToPosition> SysPersonToPosition
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SysPersonToPosition>("RightsManagementSystemModel.SysPositionSysPersonToPosition", "SysPersonToPosition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SysPersonToPosition>("RightsManagementSystemModel.SysPositionSysPersonToPosition", "SysPersonToPosition", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RightsManagementSystemModel", "SysPositionSysDepartment", "SysDepartment")]
        public SysDepartment SysDepartment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysDepartment>("RightsManagementSystemModel.SysPositionSysDepartment", "SysDepartment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysDepartment>("RightsManagementSystemModel.SysPositionSysDepartment", "SysDepartment").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SysDepartment> SysDepartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysDepartment>("RightsManagementSystemModel.SysPositionSysDepartment", "SysDepartment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SysDepartment>("RightsManagementSystemModel.SysPositionSysDepartment", "SysDepartment", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RightsManagementSystemModel", "SysPositionSysPosition", "SysPosition1")]
        public SysPosition SysPositionParent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysPosition>("RightsManagementSystemModel.SysPositionSysPosition", "SysPosition1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysPosition>("RightsManagementSystemModel.SysPositionSysPosition", "SysPosition1").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SysPosition> SysPositionParentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysPosition>("RightsManagementSystemModel.SysPositionSysPosition", "SysPosition1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SysPosition>("RightsManagementSystemModel.SysPositionSysPosition", "SysPosition1", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RightsManagementSystemModel", Name="SysRightsMenu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysRightsMenu : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SysRightsMenu 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="relate">Relate 属性的初始值。</param>
        public static SysRightsMenu CreateSysRightsMenu(global::System.String id, global::System.String name, global::System.String relate)
        {
            SysRightsMenu sysRightsMenu = new SysRightsMenu();
            sysRightsMenu.ID = id;
            sysRightsMenu.Name = name;
            sysRightsMenu.Relate = relate;
            return sysRightsMenu;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Relate
        {
            get
            {
                return _Relate;
            }
            set
            {
                OnRelateChanging(value);
                ReportPropertyChanging("Relate");
                _Relate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Relate");
                OnRelateChanged();
            }
        }
        private global::System.String _Relate;
        partial void OnRelateChanging(global::System.String value);
        partial void OnRelateChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RightsManagementSystemModel", "SysRoleToRightsSysRightsMenu", "SysRoleToRights")]
        public EntityCollection<SysRoleToRights> SysRoleToRights
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SysRoleToRights>("RightsManagementSystemModel.SysRoleToRightsSysRightsMenu", "SysRoleToRights");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SysRoleToRights>("RightsManagementSystemModel.SysRoleToRightsSysRightsMenu", "SysRoleToRights", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RightsManagementSystemModel", Name="SysRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysRole : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SysRole 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="description">Description 属性的初始值。</param>
        public static SysRole CreateSysRole(global::System.String id, global::System.String name, global::System.String description)
        {
            SysRole sysRole = new SysRole();
            sysRole.ID = id;
            sysRole.Name = name;
            sysRole.Description = description;
            return sysRole;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RightsManagementSystemModel", "SysPersonOrPositionToRoleSysRole", "SysPersonOrPositionToRole")]
        public EntityCollection<SysPersonOrPositionToRole> SysPersonOrPositionToRole
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SysPersonOrPositionToRole>("RightsManagementSystemModel.SysPersonOrPositionToRoleSysRole", "SysPersonOrPositionToRole");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SysPersonOrPositionToRole>("RightsManagementSystemModel.SysPersonOrPositionToRoleSysRole", "SysPersonOrPositionToRole", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RightsManagementSystemModel", Name="SysRoleToRights")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysRoleToRights : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SysRoleToRights 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="roleId">RoleId 属性的初始值。</param>
        /// <param name="rightsMenuID">RightsMenuID 属性的初始值。</param>
        /// <param name="operation">Operation 属性的初始值。</param>
        public static SysRoleToRights CreateSysRoleToRights(global::System.String id, global::System.String roleId, global::System.String rightsMenuID, global::System.String operation)
        {
            SysRoleToRights sysRoleToRights = new SysRoleToRights();
            sysRoleToRights.ID = id;
            sysRoleToRights.RoleId = roleId;
            sysRoleToRights.RightsMenuID = rightsMenuID;
            sysRoleToRights.Operation = operation;
            return sysRoleToRights;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private global::System.String _RoleId;
        partial void OnRoleIdChanging(global::System.String value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RightsMenuID
        {
            get
            {
                return _RightsMenuID;
            }
            set
            {
                OnRightsMenuIDChanging(value);
                ReportPropertyChanging("RightsMenuID");
                _RightsMenuID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RightsMenuID");
                OnRightsMenuIDChanged();
            }
        }
        private global::System.String _RightsMenuID;
        partial void OnRightsMenuIDChanging(global::System.String value);
        partial void OnRightsMenuIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Operation
        {
            get
            {
                return _Operation;
            }
            set
            {
                OnOperationChanging(value);
                ReportPropertyChanging("Operation");
                _Operation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Operation");
                OnOperationChanged();
            }
        }
        private global::System.String _Operation;
        partial void OnOperationChanging(global::System.String value);
        partial void OnOperationChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RightsManagementSystemModel", "SysRoleToRightsSysRightsMenu", "SysRightsMenu")]
        public SysRightsMenu SysRightsMenu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysRightsMenu>("RightsManagementSystemModel.SysRoleToRightsSysRightsMenu", "SysRightsMenu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysRightsMenu>("RightsManagementSystemModel.SysRoleToRightsSysRightsMenu", "SysRightsMenu").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SysRightsMenu> SysRightsMenuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysRightsMenu>("RightsManagementSystemModel.SysRoleToRightsSysRightsMenu", "SysRightsMenu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SysRightsMenu>("RightsManagementSystemModel.SysRoleToRightsSysRightsMenu", "SysRightsMenu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RightsManagementSystemModel", Name="SystemSetting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SystemSetting : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SystemSetting 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="value">Value 属性的初始值。</param>
        /// <param name="category">Category 属性的初始值。</param>
        /// <param name="sort">Sort 属性的初始值。</param>
        public static SystemSetting CreateSystemSetting(global::System.String id, global::System.String name, global::System.String value, global::System.String category, global::System.String sort)
        {
            SystemSetting systemSetting = new SystemSetting();
            systemSetting.ID = id;
            systemSetting.Name = name;
            systemSetting.Value = value;
            systemSetting.Category = category;
            systemSetting.Sort = sort;
            return systemSetting;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sort
        {
            get
            {
                return _Sort;
            }
            set
            {
                OnSortChanging(value);
                ReportPropertyChanging("Sort");
                _Sort = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sort");
                OnSortChanged();
            }
        }
        private global::System.String _Sort;
        partial void OnSortChanging(global::System.String value);
        partial void OnSortChanged();

        #endregion

    
    }

    #endregion

    
}
