//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace RightsManagementSystem.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(SysRightsMenu))]
    public partial class SysRoleToRights: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public string ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“ID”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _iD = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private string _iD;
    
        [DataMember]
        public string RoleId
        {
            get { return _roleId; }
            set
            {
                if (_roleId != value)
                {
                    _roleId = value;
                    OnPropertyChanged("RoleId");
                }
            }
        }
        private string _roleId;
    
        [DataMember]
        public string RightsMenuID
        {
            get { return _rightsMenuID; }
            set
            {
                if (_rightsMenuID != value)
                {
                    ChangeTracker.RecordOriginalValue("RightsMenuID", _rightsMenuID);
                    if (!IsDeserializing)
                    {
                        if (SysRightsMenu != null && SysRightsMenu.ID != value)
                        {
                            SysRightsMenu = null;
                        }
                    }
                    _rightsMenuID = value;
                    OnPropertyChanged("RightsMenuID");
                }
            }
        }
        private string _rightsMenuID;
    
        [DataMember]
        public string Operation
        {
            get { return _operation; }
            set
            {
                if (_operation != value)
                {
                    _operation = value;
                    OnPropertyChanged("Operation");
                }
            }
        }
        private string _operation;

        #endregion
        #region 导航属性
    
        [DataMember]
        public SysRightsMenu SysRightsMenu
        {
            get { return _sysRightsMenu; }
            set
            {
                if (!ReferenceEquals(_sysRightsMenu, value))
                {
                    var previousValue = _sysRightsMenu;
                    _sysRightsMenu = value;
                    FixupSysRightsMenu(previousValue);
                    OnNavigationPropertyChanged("SysRightsMenu");
                }
            }
        }
        private SysRightsMenu _sysRightsMenu;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            SysRightsMenu = null;
        }

        #endregion
        #region 关联修复
    
        private void FixupSysRightsMenu(SysRightsMenu previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.SysRoleToRights.Contains(this))
            {
                previousValue.SysRoleToRights.Remove(this);
            }
    
            if (SysRightsMenu != null)
            {
                if (!SysRightsMenu.SysRoleToRights.Contains(this))
                {
                    SysRightsMenu.SysRoleToRights.Add(this);
                }
    
                RightsMenuID = SysRightsMenu.ID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("SysRightsMenu")
                    && (ChangeTracker.OriginalValues["SysRightsMenu"] == SysRightsMenu))
                {
                    ChangeTracker.OriginalValues.Remove("SysRightsMenu");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("SysRightsMenu", previousValue);
                }
                if (SysRightsMenu != null && !SysRightsMenu.ChangeTracker.ChangeTrackingEnabled)
                {
                    SysRightsMenu.StartTracking();
                }
            }
        }

        #endregion
    }
}
