//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace TestCon.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(SysDepartment))]
    public partial class SysDepartment: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public string ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“ID”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _iD = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private string _iD;
    
        [DataMember]
        public string DepartmentName
        {
            get { return _departmentName; }
            set
            {
                if (_departmentName != value)
                {
                    _departmentName = value;
                    OnPropertyChanged("DepartmentName");
                }
            }
        }
        private string _departmentName;
    
        [DataMember]
        public string Sort
        {
            get { return _sort; }
            set
            {
                if (_sort != value)
                {
                    _sort = value;
                    OnPropertyChanged("Sort");
                }
            }
        }
        private string _sort;
    
        [DataMember]
        public string Remark
        {
            get { return _remark; }
            set
            {
                if (_remark != value)
                {
                    _remark = value;
                    OnPropertyChanged("Remark");
                }
            }
        }
        private string _remark;
    
        [DataMember]
        public string Status
        {
            get { return _status; }
            set
            {
                if (_status != value)
                {
                    _status = value;
                    OnPropertyChanged("Status");
                }
            }
        }
        private string _status;

        #endregion
        #region 导航属性
    
        [DataMember]
        public TrackableCollection<SysDepartment> SysDepartment1
        {
            get
            {
                if (_sysDepartment1 == null)
                {
                    _sysDepartment1 = new TrackableCollection<SysDepartment>();
                    _sysDepartment1.CollectionChanged += FixupSysDepartment1;
                }
                return _sysDepartment1;
            }
            set
            {
                if (!ReferenceEquals(_sysDepartment1, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("当启用 ChangeTracking 时，无法设置 FixupChangeTrackingCollection");
                    }
                    if (_sysDepartment1 != null)
                    {
                        _sysDepartment1.CollectionChanged -= FixupSysDepartment1;
                    }
                    _sysDepartment1 = value;
                    if (_sysDepartment1 != null)
                    {
                        _sysDepartment1.CollectionChanged += FixupSysDepartment1;
                    }
                    OnNavigationPropertyChanged("SysDepartment1");
                }
            }
        }
        private TrackableCollection<SysDepartment> _sysDepartment1;
    
        [DataMember]
        public SysDepartment SysDepartment2
        {
            get { return _sysDepartment2; }
            set
            {
                if (!ReferenceEquals(_sysDepartment2, value))
                {
                    var previousValue = _sysDepartment2;
                    _sysDepartment2 = value;
                    FixupSysDepartment2(previousValue);
                    OnNavigationPropertyChanged("SysDepartment2");
                }
            }
        }
        private SysDepartment _sysDepartment2;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            SysDepartment1.Clear();
            SysDepartment2 = null;
            FixupSysDepartment2Keys();
        }

        #endregion
        #region 关联修复
    
        private void FixupSysDepartment2(SysDepartment previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.SysDepartment1.Contains(this))
            {
                previousValue.SysDepartment1.Remove(this);
            }
    
            if (SysDepartment2 != null)
            {
                if (!SysDepartment2.SysDepartment1.Contains(this))
                {
                    SysDepartment2.SysDepartment1.Add(this);
                }
    
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("SysDepartment2")
                    && (ChangeTracker.OriginalValues["SysDepartment2"] == SysDepartment2))
                {
                    ChangeTracker.OriginalValues.Remove("SysDepartment2");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("SysDepartment2", previousValue);
                }
                if (SysDepartment2 != null && !SysDepartment2.ChangeTracker.ChangeTrackingEnabled)
                {
                    SysDepartment2.StartTracking();
                }
                FixupSysDepartment2Keys();
            }
        }
    
        private void FixupSysDepartment2Keys()
        {
            const string IDKeyName = "SysDepartment2.ID";
    
            if(ChangeTracker.ExtendedProperties.ContainsKey(IDKeyName))
            {
                if(SysDepartment2 == null ||
                   !Equals(ChangeTracker.ExtendedProperties[IDKeyName], SysDepartment2.ID))
                {
                    ChangeTracker.RecordOriginalValue(IDKeyName, ChangeTracker.ExtendedProperties[IDKeyName]);
                }
                ChangeTracker.ExtendedProperties.Remove(IDKeyName);
            }
        }
    
        private void FixupSysDepartment1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (SysDepartment item in e.NewItems)
                {
                    item.SysDepartment2 = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("SysDepartment1", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SysDepartment item in e.OldItems)
                {
                    if (ReferenceEquals(item.SysDepartment2, this))
                    {
                        item.SysDepartment2 = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("SysDepartment1", item);
                    }
                }
            }
        }

        #endregion
    }
}
